export interface CountryData {
  code: string;
  flag: string;
  name: string;
  isoCode: string;
}

export const countryList: CountryData[] = [
  { code: '+93', flag: '🇦🇫', name: 'Afghanistan', isoCode: 'AF' },
  { code: '+355', flag: '🇦🇱', name: 'Albania', isoCode: 'AL' },
  { code: '+213', flag: '🇩🇿', name: 'Algeria', isoCode: 'DZ' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra', isoCode: 'AD' },
  { code: '+244', flag: '🇦🇴', name: 'Angola', isoCode: 'AO' },
  { code: '+54', flag: '🇦🇷', name: 'Argentina', isoCode: 'AR' },
  { code: '+374', flag: '🇦🇲', name: 'Armenia', isoCode: 'AM' },
  { code: '+61', flag: '🇦🇺', name: 'Australia', isoCode: 'AU' },
  { code: '+43', flag: '🇦🇹', name: 'Austria', isoCode: 'AT' },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaijan', isoCode: 'AZ' },
  { code: '+973', flag: '🇧🇭', name: 'Bahrain', isoCode: 'BH' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladesh', isoCode: 'BD' },
  { code: '+375', flag: '🇧🇾', name: 'Belarus', isoCode: 'BY' },
  { code: '+32', flag: '🇧🇪', name: 'Belgium', isoCode: 'BE' },
  { code: '+55', flag: '🇧🇷', name: 'Brazil', isoCode: 'BR' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria', isoCode: 'BG' },
  { code: '+855', flag: '🇰🇭', name: 'Cambodia', isoCode: 'KH' },
  { code: '+1', flag: '🇨🇦', name: 'Canada', isoCode: 'CA' },
  { code: '+56', flag: '🇨🇱', name: 'Chile', isoCode: 'CL' },
  { code: '+86', flag: '🇨🇳', name: 'China', isoCode: 'CN' },
  { code: '+57', flag: '🇨🇴', name: 'Colombia', isoCode: 'CO' },
  { code: '+506', flag: '🇨🇷', name: 'Costa Rica', isoCode: 'CR' },
  { code: '+385', flag: '🇭🇷', name: 'Croatia', isoCode: 'HR' },
  { code: '+357', flag: '🇨🇾', name: 'Cyprus', isoCode: 'CY' },
  { code: '+420', flag: '🇨🇿', name: 'Czech Republic', isoCode: 'CZ' },
  { code: '+45', flag: '🇩🇰', name: 'Denmark', isoCode: 'DK' },
  { code: '+20', flag: '🇪🇬', name: 'Egypt', isoCode: 'EG' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia', isoCode: 'EE' },
  { code: '+358', flag: '🇫🇮', name: 'Finland', isoCode: 'FI' },
  { code: '+33', flag: '🇫🇷', name: 'France', isoCode: 'FR' },
  { code: '+995', flag: '🇬🇪', name: 'Georgia', isoCode: 'GE' },
  { code: '+49', flag: '🇩🇪', name: 'Germany', isoCode: 'DE' },
  { code: '+30', flag: '🇬🇷', name: 'Greece', isoCode: 'GR' },
  { code: '+852', flag: '🇭🇰', name: 'Hong Kong', isoCode: 'HK' },
  { code: '+36', flag: '🇭🇺', name: 'Hungary', isoCode: 'HU' },
  { code: '+354', flag: '🇮🇸', name: 'Iceland', isoCode: 'IS' },
  { code: '+91', flag: '🇮🇳', name: 'India', isoCode: 'IN' },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia', isoCode: 'ID' },
  { code: '+98', flag: '🇮🇷', name: 'Iran', isoCode: 'IR' },
  { code: '+353', flag: '🇮🇪', name: 'Ireland', isoCode: 'IE' },
  { code: '+972', flag: '🇮🇱', name: 'Israel', isoCode: 'IL' },
  { code: '+39', flag: '🇮🇹', name: 'Italy', isoCode: 'IT' },
  { code: '+81', flag: '🇯🇵', name: 'Japan', isoCode: 'JP' },
  { code: '+7', flag: '🇰🇿', name: 'Kazakhstan', isoCode: 'KZ' },
  { code: '+82', flag: '🇰🇷', name: 'South Korea', isoCode: 'KR' },
  { code: '+371', flag: '🇱🇻', name: 'Latvia', isoCode: 'LV' },
  { code: '+961', flag: '🇱🇧', name: 'Lebanon', isoCode: 'LB' },
  { code: '+370', flag: '🇱🇹', name: 'Lithuania', isoCode: 'LT' },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg', isoCode: 'LU' },
  { code: '+60', flag: '🇲🇾', name: 'Malaysia', isoCode: 'MY' },
  { code: '+52', flag: '🇲🇽', name: 'Mexico', isoCode: 'MX' },
  { code: '+377', flag: '🇲🇨', name: 'Monaco', isoCode: 'MC' },
  { code: '+31', flag: '🇳🇱', name: 'Netherlands', isoCode: 'NL' },
  { code: '+64', flag: '🇳🇿', name: 'New Zealand', isoCode: 'NZ' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria', isoCode: 'NG' },
  { code: '+47', flag: '🇳🇴', name: 'Norway', isoCode: 'NO' },
  { code: '+968', flag: '🇴🇲', name: 'Oman', isoCode: 'OM' },
  { code: '+92', flag: '🇵🇰', name: 'Pakistan', isoCode: 'PK' },
  { code: '+63', flag: '🇵🇭', name: 'Philippines', isoCode: 'PH' },
  { code: '+48', flag: '🇵🇱', name: 'Poland', isoCode: 'PL' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal', isoCode: 'PT' },
  { code: '+974', flag: '🇶🇦', name: 'Qatar', isoCode: 'QA' },
  { code: '+40', flag: '🇷🇴', name: 'Romania', isoCode: 'RO' },
  { code: '+7', flag: '🇷🇺', name: 'Russia', isoCode: 'RU' },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia', isoCode: 'SA' },
  { code: '+65', flag: '🇸🇬', name: 'Singapore', isoCode: 'SG' },
  { code: '+421', flag: '🇸🇰', name: 'Slovakia', isoCode: 'SK' },
  { code: '+386', flag: '🇸🇮', name: 'Slovenia', isoCode: 'SI' },
  { code: '+27', flag: '🇿🇦', name: 'South Africa', isoCode: 'ZA' },
  { code: '+34', flag: '🇪🇸', name: 'Spain', isoCode: 'ES' },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', isoCode: 'LK' },
  { code: '+46', flag: '🇸🇪', name: 'Sweden', isoCode: 'SE' },
  { code: '+41', flag: '🇨🇭', name: 'Switzerland', isoCode: 'CH' },
  { code: '+886', flag: '🇹🇼', name: 'Taiwan', isoCode: 'TW' },
  { code: '+66', flag: '🇹🇭', name: 'Thailand', isoCode: 'TH' },
  { code: '+90', flag: '🇹🇷', name: 'Turkey', isoCode: 'TR' },
  { code: '+44', flag: '🇬🇧', name: 'United Kingdom', isoCode: 'GB' },
  { code: '+1', flag: '🇺🇸', name: 'United States', isoCode: 'US' },
  { code: '+58', flag: '🇻🇪', name: 'Venezuela', isoCode: 'VE' },
  { code: '+1-684', flag: '🇦🇸', name: 'American Samoa', isoCode: 'AS' },
  { code: '+1-264', flag: '🇦🇮', name: 'Anguilla', isoCode: 'AI' },
  { code: '+672', flag: '🇦🇶', name: 'Antarctica', isoCode: 'AQ' },
  { code: '+1-268', flag: '🇦🇬', name: 'Antigua and Barbuda', isoCode: 'AG' },
  { code: '+297', flag: '🇦🇼', name: 'Aruba', isoCode: 'AW' },
  { code: '+1-246', flag: '🇧🇧', name: 'Barbados', isoCode: 'BB' },
  { code: '+501', flag: '🇧🇿', name: 'Belize', isoCode: 'BZ' },
  { code: '+229', flag: '🇧🇯', name: 'Benin', isoCode: 'BJ' },
  { code: '+1-441', flag: '🇧🇲', name: 'Bermuda', isoCode: 'BM' },
  { code: '+975', flag: '🇧🇹', name: 'Bhutan', isoCode: 'BT' },
  { code: '+591', flag: '🇧🇴', name: 'Bolivia', isoCode: 'BO' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia and Herzegovina', isoCode: 'BA' },
  { code: '+267', flag: '🇧🇼', name: 'Botswana', isoCode: 'BW' },
  { code: '+246', flag: '🇮🇴', name: 'British Indian Ocean Territory', isoCode: 'IO' },
  { code: '+1-284', flag: '🇻🇬', name: 'British Virgin Islands', isoCode: 'VG' },
  { code: '+673', flag: '🇧🇳', name: 'Brunei', isoCode: 'BN' },
  { code: '+226', flag: '🇧🇫', name: 'Burkina Faso', isoCode: 'BF' },
  { code: '+257', flag: '🇧🇮', name: 'Burundi', isoCode: 'BI' },
  { code: '+237', flag: '🇨🇲', name: 'Cameroon', isoCode: 'CM' },
  { code: '+238', flag: '🇨🇻', name: 'Cape Verde', isoCode: 'CV' },
  { code: '+1-345', flag: '🇰🇾', name: 'Cayman Islands', isoCode: 'KY' },
  { code: '+236', flag: '🇨🇫', name: 'Central African Republic', isoCode: 'CF' },
  { code: '+235', flag: '🇹🇩', name: 'Chad', isoCode: 'TD' },
  { code: '+61', flag: '🇨🇽', name: 'Christmas Island', isoCode: 'CX' },
  { code: '+61', flag: '🇨🇨', name: 'Cocos Islands', isoCode: 'CC' },
  { code: '+269', flag: '🇰🇲', name: 'Comoros', isoCode: 'KM' },
  { code: '+682', flag: '🇨🇰', name: 'Cook Islands', isoCode: 'CK' },
  { code: '+53', flag: '🇨🇺', name: 'Cuba', isoCode: 'CU' },
  { code: '+599', flag: '🇨🇼', name: 'Curacao', isoCode: 'CW' },
  { code: '+243', flag: '🇨🇩', name: 'Democratic Republic of the Congo', isoCode: 'CD' },
  { code: '+253', flag: '🇩🇯', name: 'Djibouti', isoCode: 'DJ' },
  { code: '+1-767', flag: '🇩🇲', name: 'Dominica', isoCode: 'DM' },
  { code: '+1-809', flag: '🇩🇴', name: 'Dominican Republic', isoCode: 'DO' },
  { code: '+670', flag: '🇹🇱', name: 'East Timor', isoCode: 'TL' },
  { code: '+503', flag: '🇸🇻', name: 'El Salvador', isoCode: 'SV' },
  { code: '+240', flag: '🇬🇶', name: 'Equatorial Guinea', isoCode: 'GQ' },
  { code: '+291', flag: '🇪🇷', name: 'Eritrea', isoCode: 'ER' },
  { code: '+251', flag: '🇪🇹', name: 'Ethiopia', isoCode: 'ET' },
  { code: '+500', flag: '🇫🇰', name: 'Falkland Islands', isoCode: 'FK' },
  { code: '+298', flag: '🇫🇴', name: 'Faroe Islands', isoCode: 'FO' },
  { code: '+679', flag: '🇫🇯', name: 'Fiji', isoCode: 'FJ' },
  { code: '+689', flag: '🇵🇫', name: 'French Polynesia', isoCode: 'PF' },
  { code: '+241', flag: '🇬🇦', name: 'Gabon', isoCode: 'GA' },
  { code: '+220', flag: '🇬🇲', name: 'Gambia', isoCode: 'GM' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana', isoCode: 'GH' },
  { code: '+350', flag: '🇬🇮', name: 'Gibraltar', isoCode: 'GI' },
  { code: '+299', flag: '🇬🇱', name: 'Greenland', isoCode: 'GL' },
  { code: '+1-473', flag: '🇬🇩', name: 'Grenada', isoCode: 'GD' },
  { code: '+1-671', flag: '🇬🇺', name: 'Guam', isoCode: 'GU' },
  { code: '+502', flag: '🇬🇹', name: 'Guatemala', isoCode: 'GT' },
  { code: '+44-1481', flag: '🇬🇬', name: 'Guernsey', isoCode: 'GG' },
  { code: '+224', flag: '🇬🇳', name: 'Guinea', isoCode: 'GN' },
  { code: '+245', flag: '🇬🇼', name: 'Guinea-Bissau', isoCode: 'GW' },
  { code: '+592', flag: '🇬🇾', name: 'Guyana', isoCode: 'GY' },
  { code: '+509', flag: '🇭🇹', name: 'Haiti', isoCode: 'HT' },
  { code: '+504', flag: '🇭🇳', name: 'Honduras', isoCode: 'HN' },
  { code: '+964', flag: '🇮🇶', name: 'Iraq', isoCode: 'IQ' },
  { code: '+44-1624', flag: '🇮🇲', name: 'Isle of Man', isoCode: 'IM' },
  { code: '+225', flag: '🇨🇮', name: 'Ivory Coast', isoCode: 'CI' },
  { code: '+44-1534', flag: '🇯🇪', name: 'Jersey', isoCode: 'JE' },
  { code: '+962', flag: '🇯🇴', name: 'Jordan', isoCode: 'JO' },
  { code: '+254', flag: '🇰🇪', name: 'Kenya', isoCode: 'KE' },
  { code: '+686', flag: '🇰🇮', name: 'Kiribati', isoCode: 'KI' },
  { code: '+383', flag: '🇽🇰', name: 'Kosovo', isoCode: 'XK' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait', isoCode: 'KW' },
  { code: '+996', flag: '🇰🇬', name: 'Kyrgyzstan', isoCode: 'KG' },
  { code: '+856', flag: '🇱🇦', name: 'Laos', isoCode: 'LA' },
  { code: '+266', flag: '🇱🇸', name: 'Lesotho', isoCode: 'LS' },
  { code: '+231', flag: '🇱🇷', name: 'Liberia', isoCode: 'LR' },
  { code: '+218', flag: '🇱🇾', name: 'Libya', isoCode: 'LY' },
  { code: '+423', flag: '🇱🇮', name: 'Liechtenstein', isoCode: 'LI' },
  { code: '+853', flag: '🇲🇴', name: 'Macau', isoCode: 'MO' },
  { code: '+389', flag: '🇲🇰', name: 'Macedonia', isoCode: 'MK' },
  { code: '+261', flag: '🇲🇬', name: 'Madagascar', isoCode: 'MG' },
  { code: '+265', flag: '🇲🇼', name: 'Malawi', isoCode: 'MW' },
  { code: '+960', flag: '🇲🇻', name: 'Maldives', isoCode: 'MV' },
  { code: '+223', flag: '🇲🇱', name: 'Mali', isoCode: 'ML' },
  { code: '+356', flag: '🇲🇹', name: 'Malta', isoCode: 'MT' },
  { code: '+692', flag: '🇲🇭', name: 'Marshall Islands', isoCode: 'MH' },
  { code: '+222', flag: '🇲🇷', name: 'Mauritania', isoCode: 'MR' },
  { code: '+230', flag: '🇲🇺', name: 'Mauritius', isoCode: 'MU' },
  { code: '+262', flag: '🇾🇹', name: 'Mayotte', isoCode: 'YT' },
  { code: '+691', flag: '🇫🇲', name: 'Micronesia', isoCode: 'FM' },
  { code: '+373', flag: '🇲🇩', name: 'Moldova', isoCode: 'MD' },
  { code: '+976', flag: '🇲🇳', name: 'Mongolia', isoCode: 'MN' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro', isoCode: 'ME' },
  { code: '+1-664', flag: '🇲🇸', name: 'Montserrat', isoCode: 'MS' },
  { code: '+212', flag: '🇲🇦', name: 'Morocco', isoCode: 'MA' },
  { code: '+258', flag: '🇲🇿', name: 'Mozambique', isoCode: 'MZ' },
  { code: '+95', flag: '🇲🇲', name: 'Myanmar', isoCode: 'MM' },
  { code: '+264', flag: '🇳🇦', name: 'Namibia', isoCode: 'NA' },
  { code: '+216', flag: '🇹🇳', name: 'Tunisia', isoCode: 'TN' },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistan', isoCode: 'TM' },
  { code: '+1-649', flag: '🇹🇨', name: 'Turks and Caicos Islands', isoCode: 'TC' },
  { code: '+688', flag: '🇹🇻', name: 'Tuvalu', isoCode: 'TV' },
  { code: '+1-340', flag: '🇻🇮', name: 'U.S. Virgin Islands', isoCode: 'VI' },
  { code: '+256', flag: '🇺🇬', name: 'Uganda', isoCode: 'UG' },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine', isoCode: 'UA' },
  { code: '+971', flag: '🇦🇪', name: 'United Arab Emirates', isoCode: 'AE' },
  { code: '+598', flag: '🇺🇾', name: 'Uruguay', isoCode: 'UY' },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistan', isoCode: 'UZ' },
  { code: '+678', flag: '🇻🇺', name: 'Vanuatu', isoCode: 'VU' },
  { code: '+379', flag: '🇻🇦', name: 'Vatican', isoCode: 'VA' },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam', isoCode: 'VN' },
  { code: '+681', flag: '🇼🇫', name: 'Wallis and Futuna', isoCode: 'WF' },
  { code: '+212', flag: '🇪🇭', name: 'Western Sahara', isoCode: 'EH' },
  { code: '+967', flag: '🇾🇪', name: 'Yemen', isoCode: 'YE' },
  { code: '+260', flag: '🇿🇲', name: 'Zambia', isoCode: 'ZM' },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabwe', isoCode: 'ZW' },
  { code: '+674', flag: '🇳🇷', name: 'Nauru', isoCode: 'NR' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal', isoCode: 'NP' },
  { code: '+599', flag: '🇦🇳', name: 'Netherlands Antilles', isoCode: 'AN' },
  { code: '+687', flag: '🇳🇨', name: 'New Caledonia', isoCode: 'NC' },
  { code: '+505', flag: '🇳🇮', name: 'Nicaragua', isoCode: 'NI' },
  { code: '+227', flag: '🇳🇪', name: 'Niger', isoCode: 'NE' },
  { code: '+683', flag: '🇳🇺', name: 'Niue', isoCode: 'NU' },
  { code: '+850', flag: '🇰🇵', name: 'North Korea', isoCode: 'KP' },
  { code: '+1-670', flag: '🇲🇵', name: 'Northern Mariana Islands', isoCode: 'MP' },
  { code: '+680', flag: '🇵🇼', name: 'Palau', isoCode: 'PW' },
  { code: '+970', flag: '🇵🇸', name: 'Palestine', isoCode: 'PS' },
  { code: '+507', flag: '🇵🇦', name: 'Panama', isoCode: 'PA' },
  { code: '+675', flag: '🇵🇬', name: 'Papua New Guinea', isoCode: 'PG' },
  { code: '+595', flag: '🇵🇾', name: 'Paraguay', isoCode: 'PY' },
  { code: '+51', flag: '🇵🇪', name: 'Peru', isoCode: 'PE' },
  { code: '+64', flag: '🇵🇳', name: 'Pitcairn', isoCode: 'PN' },
  { code: '+1-787', flag: '🇵🇷', name: 'Puerto Rico', isoCode: 'PR' },
  { code: '+242', flag: '🇨🇬', name: 'Republic of the Congo', isoCode: 'CG' },
  { code: '+262', flag: '🇷🇪', name: 'Reunion', isoCode: 'RE' },
  { code: '+250', flag: '🇷🇼', name: 'Rwanda', isoCode: 'RW' },
  { code: '+590', flag: '🇧🇱', name: 'Saint Barthelemy', isoCode: 'BL' },
  { code: '+290', flag: '🇸🇭', name: 'Saint Helena', isoCode: 'SH' },
  { code: '+1-869', flag: '🇰🇳', name: 'Saint Kitts and Nevis', isoCode: 'KN' },
  { code: '+1-758', flag: '🇱🇨', name: 'Saint Lucia', isoCode: 'LC' },
  { code: '+590', flag: '🇲🇫', name: 'Saint Martin', isoCode: 'MF' },
  { code: '+508', flag: '🇵🇲', name: 'Saint Pierre and Miquelon', isoCode: 'PM' },
  { code: '+1-784', flag: '🇻🇨', name: 'Saint Vincent and the Grenadines', isoCode: 'VC' },
  { code: '+685', flag: '🇼🇸', name: 'Samoa', isoCode: 'WS' },
  { code: '+378', flag: '🇸🇲', name: 'San Marino', isoCode: 'SM' },
  { code: '+239', flag: '🇸🇹', name: 'Sao Tome and Principe', isoCode: 'ST' },
  { code: '+221', flag: '🇸🇳', name: 'Senegal', isoCode: 'SN' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia', isoCode: 'RS' },
  { code: '+248', flag: '🇸🇨', name: 'Seychelles', isoCode: 'SC' },
  { code: '+232', flag: '🇸🇱', name: 'Sierra Leone', isoCode: 'SL' },
  { code: '+1-721', flag: '🇸🇽', name: 'Sint Maarten', isoCode: 'SX' },
  { code: '+677', flag: '🇸🇧', name: 'Solomon Islands', isoCode: 'SB' },
  { code: '+252', flag: '🇸🇴', name: 'Somalia', isoCode: 'SO' },
  { code: '+211', flag: '🇸🇸', name: 'South Sudan', isoCode: 'SS' },
  { code: '+249', flag: '🇸🇩', name: 'Sudan', isoCode: 'SD' },
  { code: '+597', flag: '🇸🇷', name: 'Suriname', isoCode: 'SR' },
  { code: '+47', flag: '🇸🇯', name: 'Svalbard and Jan Mayen', isoCode: 'SJ' },
  { code: '+268', flag: '🇸🇿', name: 'Swaziland', isoCode: 'SZ' },
  { code: '+963', flag: '🇸🇾', name: 'Syria', isoCode: 'SY' },
  { code: '+992', flag: '🇹🇯', name: 'Tajikistan', isoCode: 'TJ' },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania', isoCode: 'TZ' },
  { code: '+228', flag: '🇹🇬', name: 'Togo', isoCode: 'TG' },
  { code: '+690', flag: '🇹🇰', name: 'Tokelau', isoCode: 'TK' },
  { code: '+676', flag: '🇹🇴', name: 'Tonga', isoCode: 'TO' },
  { code: '+1-868', flag: '🇹🇹', name: 'Trinidad and Tobago', isoCode: 'TT' }
].sort((a, b) => a.name.localeCompare(b.name));


